[package]
name = "EmbedrProtocolLibrary"
version = "0.0.1"
published-at = "0xacd21943c6509b5d3f2104d9b28cc9bb7ce73a89c09f2168d579a2a844eab606"

[dependencies]
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "framework/devnet" }
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/devnet"  }

[addresses]
std = "0x1"
sui =  "0x2"
library = "0xacd21943c6509b5d3f2104d9b28cc9bb7ce73a89c09f2168d579a2a844eab606"
