[package]
name = "EmbedrProtocolLibrary"
version = "0.0.1"
published-at = "0x3f0f0e2dd1696cda820a9807b096749c212dd10103252cf9621f32ad32078867"

[dependencies]
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "framework/testnet" }
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet"  }

[addresses]
std = "0x1"
sui =  "0x2"
library = "0x3f0f0e2dd1696cda820a9807b096749c212dd10103252cf9621f32ad32078867"
