[package]
name = "EmbedrProtocolOracles"
version = "0.0.1"
published-at = "0x6e2a5847a127ede8510d6c984bdf07063e359429b99e2ab3bc5182d7871753ec"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.14.2" }
SupraOracle = { git = "https://github.com/Entropy-Foundation/dora-interface", subdir = "sui/testnet/supra_holder", rev = "51c1875d86f20abe2a22e8d2ae7a3a2a2a56d5a1" }

[addresses]
oracles = "0x6e2a5847a127ede8510d6c984bdf07063e359429b99e2ab3bc5182d7871753ec"
