[package]
name = "EmbedrProtocolStableCoinFactory"
version = "0.0.1"
published-at = "0x0"

[dependencies]
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "testnet-v1.14.2" }
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.14.2" }
SupraOracle = { git = "https://github.com/Entropy-Foundation/dora-interface", subdir = "sui/testnet/supra_holder", rev = "51c1875d86f20abe2a22e8d2ae7a3a2a2a56d5a1" }
EmbedrProtocolLibrary = { local = "../library" }
EmbedrProtocolTokens = { local = "../tokens" }
EmbedrProtocolOracles = { local = "../oracles" }

[addresses]
std = "0x1"
sui = "0x2"
stable_coin_factory = "0x0"
