[package]
name = "EmbedrProtocolLibrary"
version = "0.0.1"

[dependencies]
# FIXME: rev should be the latest devnet branch
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "b09ef4e" }
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "b09ef4e"  }

[addresses]
std = "0x1"
sui =  "0x2"
library = "0x3"