[package]
name = "EmbedrProtocolParticipationBankFactory"
version = "0.0.1"
published-at = "0xe8b01c7d4b6f348256860784ccc85eb9a74886a05d7bd66876a0a67972389fda"

[dependencies]
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "framework/testnet" }
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
EmbedrProtocolLibrary = { local = "../library" }
EmbedrProtocolTokens = { local = "../tokens" }
EmbedrProtocolStableCoinFactory = { local = "../stable_coin_factory" }

[addresses]
std = "0x1"
sui = "0x2"
participation_bank_factory = "0xe8b01c7d4b6f348256860784ccc85eb9a74886a05d7bd66876a0a67972389fda"
